config/routes.rb
Rpglogger::Application.routes.draw do
  root :to => 'log_books#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  
  resource :sessions
  resource :account, :controller => "users"
  
  resources :games, :users

  resources :log_books do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :sections
    resources :shares
  end
  
  resources :sections do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :section_properties do
      put :archive, on: :member
      put :restore, on: :member
    end
    
    resources :world_objects do
      put :archive, on: :member
      put :restore, on: :member
      
      resources :world_object_properties
    end
  end
  
end

app/views/partials/_about.haml
-if @section
  =render :partial => 'partials/log_book_nav', :locals=>{:log_book=>@section.log_book}
-elsif @log_book && !@log_book.new_record?
  =render :partial => 'partials/log_book_nav', :locals=>{:log_book=>@log_book}
-else
  %p
    <span class="brand">rpglogger</span> lets you catalog everything you <em>see</em>, everywhere you <em>go</em>, and everything you <em>do</em> in a game

app/views/partials/_log_book_nav.haml
%h2=truncate(log_book.title, length: 22)
%br
%ul{:class => "nav nav-list"}
  -if current_user && current_user.can_fully_manage?(log_book)
    %li.nav-header
      Manage
    %li
      =link_to 'Edit', edit_log_book_path(log_book)
  %li.nav-header
    Sections
  -log_book.sections.active.each do |s|
    %li=link_to s.name, section_path(s)

app/views/partials/_section_detail.haml
%table.table.table-condensed
  %thead
    %th='Name/Title'
    -section.section_properties.active.each do |sp|
      %th{class: 'column-' + sp.data_type}=sp.name
    %th=link_to("✚", new_section_world_object_path(section.id)) if @can_manage_world_objects
    
  -visible_world_objects.each do |obj|
    %tr{class: '' + (obj.archived? ? 'archived' : '')}
      %td=world_object_title_or_link(obj, @can_manage_world_objects)
      -obj.world_object_properties.each do |prop|
        -case prop.section_property.data_type
          -when 'image'
            %td{class: "column-#{prop.section_property.data_type}-thumb"}=link_to image_tag(prop.image_value_url(:thumb).to_s), prop.image_value_url if prop.image_value.present?
          -when 'text'
            %td{class: 'column-' + prop.section_property.data_type}=rpglogger_parse(prop.raw_value)
          -else
            %td{class: 'column-' + prop.section_property.data_type}=markdown_parse(prop.raw_value)
      %td=archive_or_restore_world_object(obj, @can_manage_world_objects)

app/views/partials/_section_filter.haml
#filter_box
  %input{:class=>"narrow-input", :type => "text", :value => "filter box (not yet implemented)"}

app/views/partials/_section_meta.haml
#section-meta
  <b>META information</b><br />
  <br />
  statistics<br />
  images<br />
  etc., etc.<br />

app/views/partials/_section_title.haml
.row-fluid
  .span7
    %h1=@section.name
  .span5
    .btn-toolbar.pull-right
      .btn-group
        -if current_user && current_user.can_fully_manage?(@section.log_book)
          =link_to " Edit columns".html_safe, edit_section_path(@section), :class => "btn btn-neutral btn-mini icon-pencil"
      .btn-group
        -if current_user && current_user.can_manage_world_objects_in?(@section.log_book)
          -if @show_archived_objects
            =link_to " Hide archived".html_safe, section_path(@section.id), :class => "btn btn-danger btn-mini icon-eye-close"
          -else
            =link_to " Show archived".html_safe, section_path(@section.id, show_archived: true), :class => "btn btn-success btn-mini icon-eye-open"

app/views/partials/_site_flash_and_shoutout.haml
#alert_space{:class => "row-fluid"}
  .span12
    -if flash[:notice]
      %div{:class => "alert alert-success"}
        %button{:class => "close", :data => {:dismiss => "alert"}}
          x
        =flash[:notice]
    -if flash[:error] 
      %div{:class => "alert alert-error"}
        %button{:class => "close", :data => {:dismiss => "alert"}}
          x
        =flash[:error]
    -if @log_book && @log_book.errors.any?
      %div{:class => "alert alert-block alert-error"}
        %button{:class => "close", :data => {:dismiss => "alert"}}
          x
        %h4.alert-heading
          Whoa, we got some issues here:
        %ul
          -@log_book.errors.full_messages.each do |msg|
            %li=msg
    -if @world_object && @world_object.errors.any?
      .alert.alert-block.alert-error
        %button{:class => "close", :data => {:dismiss => "alert"}}
          x
        %h4.alert-heading
          Whoa, we got some issues here:
        %ul
          -@world_object.errors.full_messages.each do |msg|
            %li=msg

app/views/partials/_skyrim_shoutout.haml
%center
  %b
    %span{:class=>'small-caps-serif'}
      celebrating the launch of
      =link_to 'elder scrolls v: skyrim', 'http://www.elderscrolls.com'

app/views/partials/_top_section_info.haml
%div{:class=>'navbar navbar-fixed-top'}
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{:href => ".nav-collapse", :data => {:toggle => "collapse"}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to 'rpglogger'.html_safe, root_path, :class => 'brand'
      %p{:class => 'navbar-text pull-left'}
        ="#{ApplicationController::APP_VERSION} - Create strategy guides for any RPG. Share them with the world."
      .nav-collapse
        %ul{:class => "nav pull-right"}
          -if current_user
            %li.dropdown{:id => "user-menu"}
              %a.dropdown-toggle{:href => "#user-menu", :data => {:toggle => "dropdown"}}
                <i class="icon-user">&nbsp;</i>
                =username_for_top_section(current_user)
                &nbsp;<i class="caret"></i>
              %ul.dropdown-menu
                %li=current_user.nickname.nil? ? (link_to 'Logout', signout_path) : (link_to 'Logout', signout_path)
          -else
            %li=link_to 'Login', '/sessions/new'