config/routes.rb
Rpglogger::Application.routes.draw do
  root :to => 'log_books#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  
  resource :sessions
  resource :account, :controller => "users"
  
  resources :games, :users

  resources :log_books do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :sections
    resources :shares
  end
  
  resources :sections do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :section_properties do
      put :archive, on: :member
      put :restore, on: :member
    end
    
    resources :world_objects do
      put :archive, on: :member
      put :restore, on: :member
      
      resources :world_object_properties
    end
  end
  
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :log_book
  
  has_many :world_objects, order: "LOWER(name) ASC", dependent: :destroy
  has_many :section_properties, order: :sort_order, dependent: :destroy
  
  accepts_nested_attributes_for :section_properties
  accepts_nested_attributes_for :world_objects
  
  validates :name, :presence => true
  
  scope :order_by_name, order("LOWER(name) ASC")
  scope :active, where("sections.archived_at IS NULL")
  scope :archived, where("sections.archived_at IS NOT NULL")
    
  def is_public?
    log_book.is_public?
  end
  
  def archived?
    archived_at != nil
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id], select: "id, log_book_id, name, archived_at")
    authorize! :show, @section.log_book

    if current_user
      HowSlow::Collector::count("views.sections.show.by-user.#{current_user.provider}.#{current_user.uid}")
    else
      HowSlow::Collector::count("views.sections.show.by-user.anonymous")
    end

    HowSlow::Collector::count("views.sections.show.total")
    HowSlow::Collector::count("views.section.show.by-section-name.#{@section.log_book.title} :: #{@section.name}]")
    
    if @section.archived?
      @section.log_book.create_empty_section if @section.log_book.does_not_have_active_sections
      return redirect_to section_path(@section.log_book.sections.active.first)
    end
      
    
    if params[:show_archived]
      @visible_world_objects = @section.world_objects.includes(world_object_properties: [:section_property]).order("LOWER(world_objects.name) ASC") # WorldObject.find_all_by_section_id(@section.id, include: [world_object_properties: [:section_property]], order: "LOWER(world_objects.name) ASC")
      @show_archived_objects = params[:show_archived]
    else
      @visible_world_objects = @section.world_objects.active.includes(world_object_properties: [:section_property]).order("LOWER(world_objects.name) ASC") # WorldObject.find_all_by_section_id(@section.id, conditions: "archived_at IS NULL", include: [world_object_properties: [:section_property]])
    end
    
    @can_manage_world_objects = current_user && current_user.can_manage_world_objects_in?(@section.log_book)
  end
  
  def edit
    @section = Section.find(params[:id])
    authorize! :edit, @section.log_book
    
    if params[:show_archived]
      @show_deleted_properties = params[:show_archived]
      @list_of_properties = @section.section_properties.sort_order
    else
      @list_of_properties = SectionProperty.active.where(["section_id = ?", @section.id]).order("sort_order ASC")
    end
  end
  
  def update
    @section = Section.find(params[:id])
    authorize! :update, @section.log_book
    
    @section.update_attributes(params[:section])
    
    new_section_property_names = params[:section_properties][:new_section_property_names]
    if new_section_property_names.present?
      highest_sort_order = @section.section_properties.collect{|sp| sp.sort_order}.max || 0
      create_new_section_and_world_object_properties_from(new_section_property_names, params[:data_type], highest_sort_order)
    end
    
    redirect_to edit_section_path(@section), notice: "Section updated"
  end
  
  def destroy
    @section = Section.find(params[:id])
    authorize! :destroy, @section.log_book
    
    log_book = @section.log_book
    @section.destroy
    
    redirect_back_or edit_log_book_path(log_book), notice: "Section deleted"
  end
  
  def archive
    @section = Section.find(params[:id])
    authorize! :archive, @section.log_book
    
    @section.update_attribute(:archived_at, Time.now)
    
    redirect_back_or edit_log_book_path(@section.log_book), notice: "Section archived (<a href=\"#{restore_section_path(@section.id)}\" data-method=\"put\">undo</a>)".html_safe
    
  end
  
  def restore
    @section = Section.find(params[:id])
    authorize! :restore, @section.log_book
    
    @section.update_attribute(:archived_at, nil)
    
    redirect_back_or edit_log_book_path(@section.log_book), notice: "Section restored"
  end
  
  private
    def create_new_sections_from(comma_separated_list_of_names)
      new_section_names = comma_separated_list_of_names.split(',').collect{|s| s.strip}.each do |name|
        Section.create(:name=>name, :log_book_id=>@log_book.id) unless name.empty? || name.blank?
      end
    end
    
    def create_new_section_and_world_object_properties_from(comma_separated_list_of_names, data_type, highest_sort_order)
      new_section_names = comma_separated_list_of_names.split(',').collect{|s| s.strip}.each_with_index do |name, index|
        new_section_property = SectionProperty.create(:name=>name, :data_type=>data_type, :sort_order=>highest_sort_order+index+1, :section_id=>@section.id) unless name.empty? || name.blank?
        
        @section.world_objects.each do |obj|
          WorldObjectProperty.create(:section_property=>new_section_property, :world_object=>obj, :boolean_value=>false)
        end
      end
    end
  
end

app/views/sections/_section_world_objects_list.haml
-section.world_objects.sorted_by_title.each do |obj|
  %tr
    -if current_user && current_user.can_manage_world_objects_in?(section.log_book)
      %td=link_to "\u2716", archive_section_world_object_path(section, obj), method: :put
      %td=link_to markdown_parse(obj.name), edit_section_world_object_path(section, obj)
    -else
      %td=markdown_parse(obj.name)
    -obj.world_object_properties.each do |prop|
      %td{:class=>'column-' + prop.section_property.data_type}=markdown_parse(prop.raw_value)

app/views/sections/edit.haml
.row_fluid
  .span7
    %h1=link_to "editing&nbsp;#{@section.name}".html_safe, section_path(@section)
  .span5
    .btn-toolbar.pull-right
      .btn-group
        -if current_user && current_user.can_fully_manage?(@section.log_book)
          -if @show_deleted_properties
            =link_to "Hide archived attributes", edit_section_path(@section.id), :class => "btn btn-danger"
          -else
            =link_to "Show archived attributes", edit_section_path(@section.id, show_archived: true), :class => "btn btn-success btn-primary"
=form_for @section, :html => {:class => "form-horizontal"} do |section_form|
  .row-fluid
    .span6
      %fieldset
        %h3
          Section Title
        =section_form.text_field :name, :html => {:class => "span3"}
      %fieldset
        %h3
          Section Attributes
        -@list_of_properties.each do |property|
          =section_form.fields_for :section_properties, property do |property_form|
            =property_form.text_field :name
            -if property.archived?
              =link_to 'Restore', restore_section_section_property_path(@section.id, property.id), :method => :put, :class => 'btn btn-success'
            -else
              =link_to 'Archive', archive_section_section_property_path(@section.id, property.id), :method => :put, :class => 'btn btn-danger'
            %p.help-block
              ="The above attribute is of type #{property_form.object.data_type}".html_safe
            %br
    .span6
      %h3
        New Attributes 
        %label='(comma-separated)'
      %fieldset
        =fields_for :section_properties do |new_section_properties_form|
          =new_section_properties_form.text_field :new_section_property_names
          %label
            Attribute Type
          =collection_select new_section_properties_form.object, :data_type, SectionProperty.all_data_types, :to_s, :to_s
      %br
      =section_form.submit "Update attributes", :class => 'btn btn-primary btn-neutral'

app/views/sections/show.haml
=render :partial => 'partials/section_title'
=render :partial => 'partials/section_detail', locals: {section: @section, visible_world_objects: @visible_world_objects, can_manage_world_objects: @can_manage_world_objects}