config/routes.rb
Rpglogger::Application.routes.draw do
  root :to => 'log_books#index'

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  
  resource :sessions
  resource :account, :controller => "users"
  
  resources :games, :users

  resources :log_books do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :sections
    resources :shares
  end
  
  resources :sections do
    put :archive, on: :member
    put :restore, on: :member
    
    resources :section_properties do
      put :archive, on: :member
      put :restore, on: :member
    end
    
    resources :world_objects do
      put :archive, on: :member
      put :restore, on: :member
      
      resources :world_object_properties
    end
  end
  
end

app/models/log_book.rb
class LogBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  
  has_many :shares, dependent: :destroy
  has_many :shared_users, through: :shares
  has_many :sections, order: :name, dependent: :destroy
  has_many :world_objects, through: :sections
  
  validates :title, :presence => true
  
  scope :public, where(["is_public = ?", true])
  scope :active, where("log_books.archived_at IS NULL")
  scope :archived, where("log_books.archived_at IS NOT NULL")
  scope :order_by_title, order("LOWER(title) ASC")
  
  accepts_nested_attributes_for :sections
  accepts_nested_attributes_for :shares
  
  def archived?
    archived_at != nil
  end
  
  def owned_by?(user)
    user_id == user.id
  end
  
  def has_active_sections
    sections.active.count != 0
  end
  
  def does_not_have_active_sections
    sections.active.count == 0
  end
  
  def create_empty_section
    empty_section = Section.create(log_book_id: self.id, name: 'New Section')
  end
  
  def create_default_sections
    locations_section  = Section.create(log_book_id: self.id, name: 'Locations')
  
    quests_section  = Section.create(log_book_id: self.id, name: 'Quests')
    quest_detail    = SectionProperty.create(section: quests_section, name: 'Detail',     data_type: 'text',    sort_order: 1)
    quest_completed = SectionProperty.create(section: quests_section, name: 'Completed?', data_type: 'boolean', sort_order: 2)
    
    journal_section = Section.create(log_book_id: self.id, name: 'Journal')
    jounral_entry   = SectionProperty.create(section: journal_section, name: 'Entry', data_type: 'text',   sort_order: 1)
  
    characters_section = Section.create(log_book_id: self.id, name: 'Characters')
    character_level = SectionProperty.create(section: characters_section, name: 'Level',      data_type: 'integer', sort_order: 1)
    character_story = SectionProperty.create(section: characters_section, name: 'Back Story', data_type: 'text',    sort_order: 2)
  end
end

app/controllers/log_books_controller.rb
class LogBooksController < ApplicationController
  def index
    authorize! :index, LogBook
    
    HowSlow::Collector::count("views.homepage")

    @public_log_books = LogBook.active.public.order_by_title
    
    if current_user
      @show_archived_items = params[:show_archived]
      @private_log_books = current_user.owned_and_shared_log_books(params[:show_archived])
    end
  end
  
  def show
    @log_book = LogBook.find(params[:id])
    authorize! :show, @log_book
    
    @log_book.create_empty_section if @log_book.sections.active.count == 0
        
    redirect_to section_path(@log_book.sections.active.order_by_name.first)
  end
  
  def new
    @log_book = LogBook.new
    authorize! :new, @log_book
    
    if !current_user
      redirect_to new_sessions_path, notice: "You must be logged in to create a logbook"
    else
      @log_book.user_id = current_user.id
    end
  end
  
  def create
    @log_book = LogBook.new(params[:log_book])
    authorize! :create, LogBook
    
    if @log_book.save
      @log_book.create_default_sections
      redirect_to @log_book, notice: "Logbook created"
    else
      render 'new'
    end
  end
  
  def edit
    @log_book = LogBook.find(params[:id])
    authorize! :edit, @log_book
    
    if params[:show_archived]
      @show_archived_sections = params[:show_archived]
      @list_of_sections = @log_book.sections.order_by_name
    else
      @list_of_sections = Section.active.where(["log_book_id = ?", @log_book.id]).order("LOWER(name) ASC")
    end
  end
  
  def update
    @log_book = LogBook.find(params[:id])
    authorize! :update, @log_book
    
    @log_book.update_attributes(params[:log_book])
    
    if (params[:sections])
      new_names = params[:sections][:new_names].split(', ').collect{|s| s.strip}.each do |new_name|
        Section.create!(:name=>new_name, :log_book_id=>@log_book.id)
      end
    end
    
    if (params[:shares])
      params[:shares][:new_google_user].delete    if params[:shares][:new_google_user].blank?
      params[:shares][:new_facebook_user].delete  if params[:shares][:new_facebook_user].blank?
      params[:shares][:new_twitter_user].delete   if params[:shares][:new_twitter_user].blank?
      
      @new_google_user    = User.find_by_nickname_and_provider(params[:shares][:new_google_user],   "google_oauth2")
      @new_facebook_user  = User.find_by_nickname_and_provider(params[:shares][:new_facebook_user], "facebook")
      @new_twitter_user   = User.find_by_nickname_and_provider(params[:shares][:new_twitter_user],  "twitter")
      
      @log_book.shared_users << @new_google_user unless @new_google_user.nil? || @log_book.shared_users.include?(@new_google_user)
      @log_book.shared_users << @new_facebook_user unless @new_facebook_user.nil? || @log_book.shared_users.include?(@new_facebook_user)
      @log_book.shared_users << @new_twitter_user unless @new_twitter_user.nil? || @log_book.shared_users.include?(@new_twitter_user)
    end
    
    if (params[:remove_shared_user_id])
      @log_book.shared_users.delete(User.find(params[:remove_shared_user_id]))
    end
    
    redirect_to edit_log_book_path(@log_book), notice: "Logbook updated"
  end
  
  def destroy
    @log_book = LogBook.find(params[:id])
    authorize! :destroy, @log_book
    
    @log_book.destroy
    
    redirect_back_or log_books_path, notice: "Logbook deleted".html_safe
  end
  
  def archive
    @log_book = LogBook.find(params[:id])
    authorize! :archive, @log_book
    
    @log_book.update_attribute(:archived_at, Time.now)
    
    redirect_back_or log_books_path, notice: "Logbook archived (<a href=\"#{restore_log_book_path(@log_book.id)}\" data-method=\"put\">undo</a>)".html_safe
  end
  
  def restore
    @log_book = LogBook.find(params[:id])
    authorize! :restore, @log_book
    
    @log_book.update_attribute(:archived_at, nil)
    
    redirect_back_or log_books_path, notice: "Logbook restored"
  end
end

app/helpers/log_book_helper.rb
# encoding: utf-8
module LogBookHelper
  def new_log_book_link
    link_to "✚", new_log_book_path
  end
  
  def archive_log_book_link(log_book)
    link_to "✖", archive_log_book_path(log_book), method: :put
  end
  
  def restore_log_book_link(log_book)
    link_to "⟲", restore_log_book_path(log_book.id), method: :put
  end
  
  def shared_log_book_icon
    "⥮"
  end
  
  def log_book_access_indicator_icon(log_book)
    if current_user
      if current_user.can_fully_manage?(log_book)
        log_book.archived? ? restore_log_book_link(log_book) : archive_log_book_link(log_book)
      elsif current_user.can_manage_world_objects_in?(log_book)
        "⥮"
      end
    end
  end
end

app/views/log_books/_log_book_sections_form.haml
.row_fluid
  .span6
    =form_for @log_book, :html => {:class => "form-horizontal"} do |log_book_form|
      %fieldset
        %label
          Log Book Title
        =log_book_form.text_field :title, :html => {:class => "span3"}
      %fieldset
        %h3
          Sections
        -list_of_sections.each do |section|
          =log_book_form.fields_for :sections, section do |section_form|
            =section_form.text_field :name, :html => {:class => "span3"}
            -if section.archived?
              =link_to 'Restore'.html_safe, restore_section_path(section.id), :method => :put, :class => 'btn btn-success'
            -else
              =link_to 'Archive'.html_safe, archive_section_path(section.id), :method => :put, :class => 'btn btn-danger'
            %p.help-block
              %br
      =log_book_form.submit 'Save sections', :class => 'btn btn-primary'
  .span6
    %h3
      New Sections
      %label='(comma-separated)'
    =form_for @log_book, :html => {:class => "form-horizontal"} do |log_book_form|
      =fields_for :sections do |new_sections_form|
        =new_sections_form.text_field :new_names, :html => {:class => "span3"}
      =log_book_form.submit "Add sections", :class => 'btn btn-primary'

app/views/log_books/_log_book_sharing_form.haml
.row-fluid
  .span12
    .page-header
      %h1
        Sharing
        %small
          -if @log_book.is_public
            =link_to "Make private", log_book_path(@log_book.id, log_book: {is_public: false}), :class => "btn btn-success btn-mini", :method => :put
          -else
            =link_to "Make public", log_book_path(@log_book.id, log_book: {is_public: true}), :class => "btn btn-danger btn-mini", :method => :put
  .row-fluid
    .span6
      %h2
        Authorized Users
      %h3
        Current Authorized Users
      -if @log_book.shared_users.count == 0
        %p
          No other users are currently authorized to edit this log book,
          -if @log_book.is_public
            though any person may read the data. 
          -else
            and the data is not publicly accessible.
      -else
        %ul
          -@log_book.shared_users.each do |shared_user|
            %li
              ="#{username_for_top_section(shared_user)}&nbsp;".html_safe
              =link_to 'Remove access', log_book_path(@log_book, remove_shared_user_id: shared_user.id), :method => :put, :class => 'btn btn-danger btn-mini'
    .span6
      =form_for @log_book do |sharing_form|
        %h3
          Add Users
        %label
          Google (e-mail address)
        .input-prepend
          %span.add-on
            <i class="icon-envelope"></i>
          =text_field_tag "shares[new_google_user]", nil, :placeholder => "example@gmail.com"
        %label
          Facebook (nickname)
        .input-prepend 
          %span.add-on
            <i class="icon-thumbs-up"></i>
          =text_field_tag "shares[new_facebook_user]", nil, :placeholder => "davidantaramian"
        %label
          Twitter (username)
        .input-prepend
          %span.add-on
            @
          =text_field_tag "shares[new_twitter_user]", nil, :placeholder => "DavidAntaramian"
        =sharing_form.submit "Add users", :class => 'styled-button-blue-gray'

app/views/log_books/_log_book_title.haml
.row-fluid
  .span7
    %h1=link_to "editing #{@log_book.title}", @log_book
  .span5
    -if @show_archived_sections
      =link_to " Hide archived sections", edit_log_book_path(@log_book.id), {class: "btn icon-eye-close btn-warning btn-mini pull-right"}
    -else
      =link_to " Show archived sections", edit_log_book_path(@log_book.id, show_archived: true), {class: "btn icon-eye-open btn-danger btn-mini pull-right"}

app/views/log_books/_log_book_title_section.haml
.section-title
  %table{width: "100%"}
    %tr
      %td.serif-sc-font.big-font-size
        ="in "
        =link_to @log_book.title, @log_book
      %td.right        
        -if @show_deleted_sections
          %td.right=link_to "Hide deleted sections", edit_log_book_path(@log_book.id), {class: "styled-button-blue-gray"}
        -else
          %td.right=link_to "Show deleted sections", edit_log_book_path(@log_book.id, show_deleted: true), {class: "styled-button-blue-gray"}

app/views/log_books/_private_log_books.haml
-if current_user
  .row-fluid
    .span7
      %h1='Your Log Books'
    .span5
      -if show_archived_items
        =link_to " Hide archived", log_books_path, {class: "btn icon-eye-close btn-danger btn-mini pull-right"}
      -else
        =link_to " Show archived", log_books_path(show_archived: true), {class: "btn icon-eye-open btn-success btn-mini pull-right"}
  .row-fluid
    .span12
      %table.table.table-condensed
        %thead
          %tr
            %th='Title'
            %th='Game'
            %th='No.&nbsp;of&nbsp;Items'.html_safe
            %th=new_log_book_link
        -private_log_books.each do |log_book|
          %tr{class: '' + (log_book.archived? ? 'archived' : '')}
            %td=log_book.archived? ? log_book.title.html_safe : link_to(log_book.title.html_safe, log_book)
            %td=log_book.game_name.html_safe
            %td=log_book.world_objects.active.count
            %td=log_book_access_indicator_icon(log_book)

app/views/log_books/_public_log_books.haml
%h1
  Public Log Books
%br
.row-fluid
  .span12
    %table.table.table-condensed
      %thead
        %th='Title'
        %th='Game'
        %th='No.&nbsp;of&nbsp;Items'.html_safe
        %th
      -public_log_books.each do |log_book|
        %tr
          %td=link_to log_book.title.html_safe, log_book
          %td=log_book.game_name.html_safe
          %td=log_book.world_objects.active.count
          %td=log_book_access_indicator_icon(log_book)

app/views/log_books/edit.haml
=render partial: "log_book_title"
=render partial: "log_book_sections_form", locals: {list_of_sections: @list_of_sections}
=render partial: "log_book_sharing_form"                

app/views/log_books/index.haml
#log-book-index
  =render partial: "private_log_books", locals: {private_log_books: @private_log_books, show_archived_items: @show_archived_items}
  =render partial: "public_log_books", locals: {public_log_books: @public_log_books}

app/views/log_books/new.haml
%h1
  New log book
=form_for @log_book do |log_book_form|
  =log_book_form.hidden_field :user_id
  %label='Log Book Title'
  =log_book_form.text_field :title, :class => "span3", :placeholder => "Celentrium of Skyrim"
  %label='Game Name'
  =log_book_form.text_field :game_name, :class => "span3", :placeholder => "Skyrim"
  %br
  =log_book_form.submit 'Create', :class=>'btn btn-success'